### ISSUE TITLE
Create documentation for Rest API

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/server#15]

**Comment by yvan-sraka** [comment]
This is solve by https://github.com/cappuccino-app/cappuccino-server/issues/16 :wink:!

**Comment by MattiaPrimavera** [comment]
I reopen it since I'm making a little .md explaination of the API for making it clearly accessible to you before we can solve #16, and to be able to discuss on how to extend it and if to have it modified ;)

**Comment by MattiaPrimavera** [comment]
Look at the .md file and tell me what you think mate @yvan-sraka

**Comment by yvan-sraka** [comment]
Which .md file? Don't want to put that in `README.md` section?

**Comment by MattiaPrimavera** [comment]
https://github.com/cappuccino-app/cappuccino-server/tree/master/cappuccino/docs/API
The file is called `commands.md`

I'm not sure about that, have a look, it takes space, and it talks about the API, so I created a `docs` directory for the moment.

**Comment by yvan-sraka** [comment]
How I see the new API is:

- Use the URL to specify the relative path between where `cppccn` command where launch and the file or the the folder you want to work on.

- Use `GET` to a folder to `ls -la` is content or to show/download (depends of the mimetype of the file and the capabilities of the browser) a text or binary file.

- Use `POST`, `DELETE`, `PUT`, etc... on a folder or a file to `cp`, `rm`, `mv`, etc...

Examples:

`GET` http://localhost:3000/dist -> `ls` a directory
`GET` http://localhost:3000/LICENSE -> download/show a text file
`DELETE` http://localhost:3000/.gitignore -> `rm .gitignore`

@MattiaPrimavera what do you think about all that comparing to the [old specifications](https://github.com/cppccn/server/tree/f46f69a7156e94555696a0cb0a312636c301216d/cappuccino/docs/API)?
