### ISSUE TITLE
Generate technical documentation

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/server#16]
http://www.sphinx-doc.org/en/stable/ is perfect for this job :smile:!

**Comment by yvan-sraka** [comment]
Because we switch from Django to Node.js + TypeScript, http://typedoc.org/ could be cool :wink:!

**Comment by yvan-sraka** [comment]
Done by commits https://github.com/cppccn/server/commit/415ea56232ae374133de5fc157fea802922cf9a9 .. https://github.com/cppccn/server/commit/8b52e03a72c062d886aebff40f3a889d8665b680!
