### ISSUE TITLE
Include headers for code rating into README.md

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/server#19]

**Comment by yvan-sraka** [comment]
@MattiaPrimavera I'm not sure to understand? Like **Travis CI** one https://github.com/cappuccino-app/cappuccino-server/issues/10 :smile:?

**Comment by yvan-sraka** [comment]
https://github.com/cappuccino-app/cappuccino-server/commit/23f5517997f49c313f3991c27768b41938bffc00

**Comment by yvan-sraka** [comment]
@MattiaPrimavera What kind of other **badges** do you want to add on the `README.md`? Can we close the issue :wink:?

**Comment by MattiaPrimavera** [comment]
Look at the read me from a friend of mine ;)
https://github.com/mrnfrancesco/wpscan

**Comment by yvan-sraka** [comment]
I create a badge for a **Gitter** chatting room :wink:!
_(nice to discuss about the project)_

**Comment by MattiaPrimavera** [comment]
Looks cool, now I'm on mobile phone though, can't see that :) I'll let u
know what I think

**Comment by MattiaPrimavera** [comment]
> Repositories:
> Public and private
> This application will be able to read and write all public and private repository data. This includes the following:
- Code 
- Issues
- Pull requests
- Wikis
- Settings
- Webhooks and services
- Deploy keys

Does it seem normal to you that [Code Climate](https://codeclimate.com) asks all this for just having a little badge showing their way of rating our code?

**Comment by yvan-sraka** [comment]
Yes, that's not just a little badge..

**Comment by MattiaPrimavera** [comment]
Aborted so. Or first we may look for something with less demands in
permissions

**Comment by yvan-sraka** [comment]
Cool, so we're agree to keep **gitter** unless you find a better solution :smile:!

**Comment by MattiaPrimavera** [comment]
Wasn't gitter only about chat?

**Comment by yvan-sraka** [comment]
Yes **gitter** is a chat used by most of open source projects found on GitHub!

**Comment by MattiaPrimavera** [comment]
So this ticket is actually about a `code rating` header to have a `rate` on our project code from an external service. I wonder if a good replacement exist for the one I wanted to use.

**Comment by yvan-sraka** [comment]
Done by commit https://github.com/cppccn/server/commit/620ad0953c39435687a27e471761cdb30fc5ec9f 🥇!
