### ISSUE TITLE
install.sh script for Prod with Apache2 + mod_wsgi

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/server#28]

**Comment by yvan-sraka** [comment]
Is that not a `high priority` issue?

**Comment by MattiaPrimavera** [comment]
It depends, we're still on development, it will be prioritary once we'd like to put that on prod, like on raspberry pi ... And I already have a working setup there actually ...

**Comment by yvan-sraka** [comment]
This issue is no longer relevant.
