### ISSUE TITLE
Add django tests for existing functionnalities

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/server#30]
- [X] Login
- [ ] Upload  
- [ ] Download  
- [x] File System commands

**Comment by MattiaPrimavera** [comment]
I check the File system commands one, since I created a singular ticket with check-list shape for every command.

**Comment by yvan-sraka** [comment]
Okay, maybe we can make a global check for all commands by executing a sample shell script we use them all! Good idea?

**Comment by yvan-sraka** [comment]
This issue is no longer relevant.
