### ISSUE TITLE
command `ls filename` error

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/server#64]
When executing an `ls filename` command to the server, what do we do?
- fetch extra informations on the file
- nothing
- we send a particular error or warning message

what do u think?

**Comment by yvan-sraka** [comment]
Not sure to understand: what would you say by:
> When executing an ls filename command to the server

:fearful:?

**Comment by MattiaPrimavera** [comment]
MMM ... we have a client that makes API requests to the server. One of this API entry points is the `command API entry point`, for which I've written a `command.md` file that you could read ;) it's gonna clarify things ...

The `command` api allows the client to send commands to the server in a subset of shell commands.
`ls filename` is one of the possible cases we have to handle when treating the command `ls`

**Comment by yvan-sraka** [comment]
This issue is no longer relevant: as said in issue https://github.com/cppccn/server/issues/15, `ls` command is just a `GET` on a folder given by the URL of the request!
