### ISSUE TITLE
Enable cd command + write tests

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/server#65]
Here follows what `cd` command should handle:
- [x] `cd .` --> return currentDir value
- [x] `cd` --> set currentDir to `local_settings.SHARED_PATH`
- [x] `cd ..` --> set currentDir to parent directory
- [x] `cd path` --> set currentDir value to path
- [ ] `cd -` --> set currentDir value to previous currentDir value
- [ ] `cd ~` --> set currentDir value to `local_settings.SHARED_PATH`

Tests:
- [x] `cd .` --> return currentDir value
- [x] `cd` --> set currentDir to `local_settings.SHARED_PATH`
- [x] `cd ..` --> set currentDir to parent directory
- [x] `cd path` --> set currentDir value to path
- [ ] `cd -` --> set currentDir value to previous currentDir value
- [ ] `cd ~` --> set currentDir value to `local_settings.SHARED_PATH`

**Comment by yvan-sraka** [comment]
This issue is no longer relevant.

The `cd` command exist through the URL routing of the server, this is the job of the client to store the `currentDirectory` variable, to follow the principle of stateless API! Do you agreed with that @MattiaPrimavera?
